---
apiVersion: v1
kind: ConfigMap
metadata:
  name: starlark-script
  namespace: telegraf
data:
  remotewrite.star: |
    def apply(metric):
        if metric.name == "prometheus_remote_write":
            for k, v in metric.fields.items():
                metric.name = k
                metric.fields["value"] = v
                metric.fields.pop(k)
        return metric
